#import '../../fragments/membership.graphql'
mutation inviteMembersMutation($boardSlug: String!, $email: String!) {
  inviteMembers(input: { boardSlug: $boardSlug, email: $email }) {
    memberships {
      ...Membership
    }
    errors {
      fullMessages
    }
  }
}

query getMembershipsQuery($boardSlug: String!) {
  memberships(boardSlug: $boardSlug) {
    ...Membership
  }
}

query getSuggestionsQuery($autocomplete: String!) {
  suggestions(autocomplete: $autocomplete) {
    users
    teams
  }
}
