mutation destroyActionItemMutation($id: ID!) {
  destroyActionItem(input: { id: $id }) {
    id
    errors {
      fullMessages
    }
  }
}

mutation updateActionItemMutation($id: ID!, $body: String!, $assigneeId: ID) {
  updateActionItem(
    input: { id: $id, attributes: { body: $body, assigneeId: $assigneeId } }
  ) {
    actionItem {
      id
    }
    errors {
      fullMessages
    }
  }
}
