#import '../../fragments/membership.graphql'
mutation toggleReadyStatusMutation($id: ID!) {
  toggleReadyStatus(
    input: { id: $id }
  ) {
    membership {
      id
    }
    errors {
      fullMessages
    }
  }
}

query getMembership($boardSlug: String!){
  membership(boardSlug: $boardSlug) {
    ...Membership
  }
}

subscription membershipUpdatedSubscription($boardSlug: String!) {
  membershipUpdated(boardSlug: $boardSlug) {
   ...Membership
  }
}
