mutation toggleReadyStatusMutation($id: ID!) {
  toggleReadyStatus(
    input: { id: $id }
  ) {
    membership {
      id
    }
    errors {
      fullMessages
    }
  }
}

query getMembershipQuery($boardSlug: String!){
  membership(boardSlug: $boardSlug) {
    id
    ready
  }
}

subscription membershipUpdatedSubscription($boardSlug: String!) {
  membershipUpdated(boardSlug: $boardSlug) {
   id
   ready
  }
}
