#import '../../fragments/action_item.graphql'
#import '../../fragments/card.graphql'
subscription actionItemAddedSubscription($boardSlug: String!) {
  actionItemAdded(boardSlug: $boardSlug) {
   ...ActionItem
  }
}

subscription actionItemMovedSubscription($boardSlug: String!) {
  actionItemMoved(boardSlug: $boardSlug) {
   ...ActionItem
  }
}

subscription actionItemDestroyedSubscription($boardSlug: String!) {
  actionItemDestroyed(boardSlug: $boardSlug) {
   id
  }
}

subscription actionItemUpdatedSubscription($boardSlug: String!) {
  actionItemUpdated(boardSlug: $boardSlug) {
   ...ActionItem
  }
}


subscription cardAddedSubscription($boardSlug: String!) {
  cardAdded(boardSlug: $boardSlug) {
   ...Card
  }
}

mutation addActionItemMutation($boardSlug: String!, $assigneeId: ID!, $body: String!) {
  addActionItem(
    input: { attributes: { boardSlug: $boardSlug, assigneeId: $assigneeId, body: $body } }
  ) {
    actionItem {
      id
    }
    errors {
      fullMessages
    }
  }
}
